### PR TITLE
Support for state `sol` of NamedTuple type

### PR DESCRIPTION
**Pull request by navidcy**
This is an attempt to deal with #212.

### CODE REVIEW

**Comment by glwagner** [comment]
The design requires `sol`, `L`, and `N` to all be `NamedTuple`s with the same names and fields.

The module writers will still provide one function `calcN!`. However they can use the tuples.

A nice convenience would be that a named tuple value of `nothing` doesn't error. That will mean that you get correct behavior when `typeof(sol.U) isa AbstractArray` or when `typeof(sol.U) isa Nothing`.

Are there any complications with `Equation` or `Problem`?

**Comment by navidcy** [comment]
`Equation` struct includes `dims` which would become a tuple of tuples I guess?
But I'm not even sure if `Equation.dims` is used...

**Comment by navidcy** [comment]
Also
https://github.com/FourierFlows/FourierFlows.jl/blob/20a68daaa00ffb2d88d95935f6efff4d86e378e7/src/problem.jl#L87
should be generalized...

**Comment by glwagner** [comment]
> Also
> https://github.com/FourierFlows/FourierFlows.jl/blob/20a68daaa00ffb2d88d95935f6efff4d86e378e7/src/problem.jl#L87
> 
> 
> should be generalized...

Won't module writers just use

```julia
solution = (u=devzeros(...), v=devzeros(...))
```

why do you need a special utility?

**Comment by navidcy** [comment]
True.

`sol` is constructed automatically based on the dimension of `L`. But I guess I answered myself; if the user prescribed `L` appropriately the everything should follow through.

**Comment by glwagner** [comment]
> True.
> 
> `sol` is constructed automatically based on the dimension of `L`. But I guess I answered myself; if the user prescribed `L` appropriately the everything should follow through.

~~user~~: "module writer", I think you mean.

**Comment by navidcy** [comment]
I'm closing this for now

**Pull request closed without merging**
