### PR TITLE
rewrites the getetdcoeffs function using arbitrary-precision arithmetic

### PR DESCRIPTION
**Pull request by navidcy**
Inspired by @ChrisRackauckas; see issue #31.

### CODE REVIEW

**Comment by navidcy** [comment]
@glwagner: do you agree with merging?

**Comment by glwagner** [comment]
My only lingering concern is that the BigFloat method is significantly slower than the Trefethen method for some problems. Is there any assurance this isn't the case?

If we aren't sure, it could make sense to preserve the Trefethen method (just as a function that takes 3 arguments instead of 2) in addition to having the new method...

**Comment by ChrisRackauckas** [comment]
There's no assurance. I was just noting what I tested and didn't do anything worthy of peer review. I'd be interested to know what problems end up being slower. Is it just problems with diagonal operators? That would make since the matrix inversion is much cheaper, so doing `N` of them for the contour integral wouldn't be as much of a burden.

**Comment by glwagner** [comment]
@ChrisRackauckas my primary difficulty is not understanding how BigFloat works. If the arithmetic is actually *arbitrary* precision, presumably that implies that calculations that require "a lot" of precision (which the ETDRK4 calculations do, since double precision is not sufficient) will also require "a lot" of computation time, and also possibly will allocate "a lot" of memory.

The BigFloat method seems like a good default and may be especially useful for non-diagonal problems, but it could be smart to keep the Kassam+Trefethen method available in reserve just in case.

**Comment by ChrisRackauckas** [comment]
>If the arithmetic is actually arbitrary precision, presumably that implies that calculations that require "a lot" of precision (which the ETDRK4 calculations do, since double precision is not sufficient) will also require "a lot" of computation time, and also possibly will allocate "a lot" of memory.

It's arbitrary precision but fixed at any time.

```julia
julia> precision(BigFloat)
256
```

but can be changed with `setprecision`. A faster alternative is to use this library:

https://github.com/saschatimme/HigherPrecision.jl

It should be much faster for the polynomial calculations, but of course the cutoff of the smallest eigenvalue allowed is increased. It would be interesting to find out whether the smallest eigenvalue that does well with 128-bit floats is <1e-16. I think it might be, in which case that's all that's needed.

Another library to know about is ArbFloats.jl.

https://github.com/JuliaArbTypes/ArbFloats.jl

It requires Nemo though so it's a much bigger dependency. However, it's a faster arbitrary precision type. But because of the dep I would avoid it in a package.

**Comment by navidcy** [comment]
@glwagner:
Yes, indeed using BigFloat is slower when `LC` is diagonal.
But `getetdcoeffs` is only called once for each! Also, I think that an implementation which is 1) simpler, 2) more straightforward and 3) requires two less parameters (`rcirc` and `M`) does have an advantage that even, may I dare say, worths some speed slowdown.

**Comment by ChrisRackauckas** [comment]
Give HigherPrecision.jl a try here though. You definitely don't need 256 bits for this. 128 double double should be enough.

**Comment by navidcy** [comment]
@ChrisRackauckas: seems like `HigherPrecision.jl` doesn't work with complex numbers...
```julia
julia> a = rand(2, 2) + im*rand(2,2); a = DoubleFloat64.(a)
ERROR: InexactError()
Stacktrace:
 [1] convert at ./complex.jl:31 [inlined]
 [2] HigherPrecision.DoubleFloat64(::Complex{Float64}) at ./sysimg.jl:77
 [3] macro expansion at ./broadcast.jl:153 [inlined]
 [4] macro expansion at ./simdloop.jl:73 [inlined]
 [5] macro expansion at ./broadcast.jl:147 [inlined]
 [6] _broadcast!(::Type{HigherPrecision.DoubleFloat64}, ::Array{HigherPrecision.DoubleFloat64{HigherPrecision.ComputeMode{:fast}},2}, ::Tuple{Tuple{Bool,Bool}}, ::Tuple{Tuple{Int64,Int64}}, ::Array{Complex{Float64},2}, ::Tuple{}, ::Type{Val{0}}, ::CartesianRange{CartesianIndex{2}}) at ./broadcast.jl:139
 [7] broadcast_t(::Type{T} where T, ::Type{T} where T, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}, ::CartesianRange{CartesianIndex{2}}, ::Array{Complex{Float64},2}) at ./broadcast.jl:268
 [8] broadcast_c at ./broadcast.jl:314 [inlined]
 [9] broadcast(::Type{T} where T, ::Array{Complex{Float64},2}) at ./broadcast.jl:434
```

**Comment by navidcy** [comment]
Indeed, using `HigherPrecision.j;` is faster. And for large matrices it beats the contour integration.

E.g. for `n=128`

```julia
julia> include("test_getetdcoeffsBigFloat.jl")
calling getetdcoeffs (contour integration)
  0.231698 seconds (88.23 k allocations: 25.536 MiB, 2.79% gc time)
calling getetdcoeffsBigFloat
  0.953281 seconds (4.08 M allocations: 184.899 MiB, 29.96% gc time)
calling getetdcoeffsDoubleFloat
  0.298950 seconds (209.32 k allocations: 10.294 MiB)

compare contour integration and getetdcoeffsBigFloat
diff error ζ: 1.0676391305427447e-16
diff error α: 8.194844633554025e-16
diff error β: 3.5498659727867634e-16
diff error Γ: 7.758316515362998e-16

compare contour integration and getetdcoeffsDoubleFloat
diff error ζ: 1.0676391305427447e-16
diff error α: 8.194844633554025e-16
diff error β: 3.5498659727867634e-16
diff error Γ: 7.758316515362998e-16
```

while for `n=1024`

```julia
calling getetdcoeffs (contour integration)
  4.533772 seconds (88.24 k allocations: 1.327 GiB, 5.72% gc time)
calling getetdcoeffsBigFloat
 37.422017 seconds (253.79 M allocations: 11.190 GiB, 26.94% gc time)
calling getetdcoeffsDoubleFloat
  2.520796 seconds (209.31 k allocations: 152.290 MiB, 29.69% gc time)

compare contour integration and getetdcoeffsBigFloat
diff error ζ: 7.040023244381022e-16
diff error α: 2.3568128447361296e-8
diff error β: 7.120884934685503e-10
diff error Γ: 7.185514439421842e-9

compare contour integration and getetdcoeffsDoubleFloat
diff error ζ: 7.040023244381022e-16
diff error α: 2.3568128447361296e-8
diff error β: 7.120884934685503e-10
diff error Γ: 7.185514439421842e-9
```

thanks @ChrisRackauckas

**Comment by glwagner** [comment]
Is there good reason to believe that the precision required for this calculation is similar for many (or all) problems?

**Comment by ChrisRackauckas** [comment]
>Is there good reason to believe that the precision required for this calculation is similar for many (or all) problems?

Do the gamma test from the paper and see if it's stable in 128-bit floats with `1e-16`.

**Comment by navidcy** [comment]
To be honest I am also skeptical as well…
Probably this just translates the problem from having to worry about `M` and `rcirc` to having to worry about whether double precision is good enough?

**Comment by ChrisRackauckas** [comment]
For non-diagonal the coefficients are computed element-wise so you can explicitly check what the smallest values this is stable for just by writing out the alpha, beta, and gamma functions of `z` and checking the results.

**Comment by ChrisRackauckas** [comment]
```julia
using HigherPrecision
f(z) = z^(-3) * (-4 -3z - z^2 + exp(z)*(4-z))
range = 0:-1:-16
A = Float64[f(z) for z in DoubleFloat64(10.0).^(range)]
for i in eachindex(A)
    println("z = 10^(-$(range[i])), γ(z) = $(A[i])")
end

range = 0:-1:-16
A = Float64[f(z) for z in big(10.0).^(range)]
for i in eachindex(A)
    println("z = 10^($(Float64(range[i]))), γ(z) = $(A[i])")
end
```

```julia
# DoublePrecision64
z = 10^(-0), γ(z) = 0.15484548537713572
z = 10^(--1), γ(z) = 0.16658049502573677
z = 10^(--2), γ(z) = 0.16666583054959325
z = 10^(--3), γ(z) = 0.16666665833055497
z = 10^(--4), γ(z) = 0.16666666658333057
z = 10^(--5), γ(z) = 0.16666666666583335
z = 10^(--6), γ(z) = 0.16666666666663651
z = 10^(--7), γ(z) = 0.1666666666859636
z = 10^(--8), γ(z) = 0.166666735661989
z = 10^(--9), γ(z) = 0.16664686622793876
z = 10^(--10), γ(z) = 0.16948183510607676
z = 10^(--11), γ(z) = 0.0
z = 10^(--12), γ(z) = -49303.80657631324
z = 10^(--13), γ(z) = 4.9303806576313235e7
z = 10^(--14), γ(z) = -2.465190328815662e10
z = 10^(--15), γ(z) = 4.9303806576313234e13
z = 10^(--16), γ(z) = 4.930380657631324e16

# BigFloat
z = 10^(0.0), γ(z) = 0.15484548537713572
z = 10^(-1.0), γ(z) = 0.16658049502573677
z = 10^(-2.0), γ(z) = 0.16666583054959325
z = 10^(-3.0), γ(z) = 0.16666665833055497
z = 10^(-4.0), γ(z) = 0.16666666658333054
z = 10^(-5.0), γ(z) = 0.16666666666583332
z = 10^(-6.0), γ(z) = 0.16666666666665833
z = 10^(-7.0), γ(z) = 0.16666666666666657
z = 10^(-8.0), γ(z) = 0.16666666666666666
z = 10^(-9.0), γ(z) = 0.16666666666666666
z = 10^(-10.0), γ(z) = 0.16666666666666666
z = 10^(-11.0), γ(z) = 0.16666666666666666
z = 10^(-12.0), γ(z) = 0.16666666666666666
z = 10^(-13.0), γ(z) = 0.16666666666666666
z = 10^(-14.0), γ(z) = 0.16666666666666666
z = 10^(-15.0), γ(z) = 0.16666666666666666
z = 10^(-16.0), γ(z) = 0.16666666666666666
```

So `DoubleFloat64` does well until about values of size `1e-9` or `1e-10`. BigFloat is more than enough to cover the whole range of Float64.

**Comment by navidcy** [comment]
I'm closing the PR for now. 

### Regarding DoubleFloat:
`HigherPrecision.jl` requires "FMA instructions"

```julia
include(joinpath(dirname(JULIA_HOME),"share","julia","build_sysimg.jl")); build_sysimg(force=true)
```
This complicates the dependencies. We decided to drop `HigherPrecision.jl` until this requirement is not needed.

### Regarding BigFloat:
We concluded that for problems with diagonal `LC`, which is currently the only problems `FourierFlows.jl` can handle, there is not much of a gain (except simplicity). Thus we won't implement `getetdcoeffs` using `BigFloat` for now.

**Comment by ChrisRackauckas** [comment]
Yup sounds good. Thanks for doing more testing.

**Pull request closed without merging**
