### PR TITLE
Drop travis and gitlab in favor of buildkite

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by glwagner** [comment]
Cool! On what machine do the tests run? Does buildkite offer free builds?

**Comment by navidcy** [comment]
Similar to Oceananigans.

**Comment by glwagner** [comment]
> Similar to Oceananigans.

We are using tartarus and sverdrup. Are we going to use this machines for FourierFlows as well? I'm ok with using sverdrup (my personal desktop) but it may not be appropriate to co-opt tartarus.

**Comment by navidcy** [comment]
To tell you the truth I have no idea where the runs are done. I just used the default config in https://github.com/JuliaGPU/buildkite. Does this answers your question?

**Comment by glwagner** [comment]
Are you certain that the tests run? Take a look at

https://github.com/CliMA/Oceananigans.jl/blob/master/.buildkite/pipeline.yml

For example, we run the GPU tests with a list of commands:

```
    commands:
      # Download julia binaries
      - "wget -N -P $SVERDRUP_HOME https://julialang-s3.julialang.org/bin/linux/x64/$JULIA_MINOR_VERSION/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
      - "tar xf $SVERDRUP_HOME/julia-$JULIA_VERSION-linux-x86_64.tar.gz -C $SVERDRUP_HOME"

      # Instantiate and precompile
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.instantiate(; verbose=true)'"
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.build()'"
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.precompile()'"
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.status()'"

      # Force the initialization of the CUDA runtime as it is lazily loaded by default
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using CUDA; CUDA.versioninfo()'"

      # Download artifacts by running an empty testgroup and thereby executing /test/runtests.jl
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
```

**Comment by navidcy** [comment]
https://buildkite.com/julialang/fourierflows-dot-jl/builds/3#7ff625c9-2a0f-47e4-b5b1-7bfd6b8598e8/3

**Comment by navidcy** [comment]
@glwagner, @maleadt might be able to tell you which machines the tests run.

**Comment by glwagner** [comment]
Oh neat, that answers my question --- this is a service provided by Julia. That's awesome. Note this is not what we use for Oceananigans, but its still great. I don't need to know _exactly_ where it runs; I was just unaware of the julia service and wanted to make sure the tests were indeed running somewhere.

**Comment by navidcy** [comment]
merge then if all looks ok (and in GeophysicalFlows.jl as well)

**Comment by maleadt** [comment]
Runs on the JuliaGPU CI servers, https://github.com/JuliaGPU/buildkite/tree/main/agents, using some Buildkite plugins I wrote: https://github.com/JuliaCI/julia-buildkite-plugin https://github.com/JuliaCI/julia-test-buildkite-plugin https://github.com/JuliaCI/julia-coverage-buildkite-plugin. Results in a much more compact pipeline definition :-)

**Pull request merged**
