### PR TITLE
Compat entry to avoid bug in CUDA v3.7.0

### PR DESCRIPTION
**Pull request by navidcy**
This PR puts an upper bound to CUDA on v3.6.4. With CUDA v3.7.0 I noticed that `mul!` was not working straight out of the box with CuArrays and (r)fftplans.

### CODE REVIEW

**Comment by navidcy** [comment]
(CUDA v3.7.0 breaking/bug was partly discussed in #309.)

**Comment by maleadt** [comment]
I'd be happy to quickly tag a bugfix release to avoid having to bound.

**Comment by navidcy** [comment]
> 

Thanks @maleadt!

Perhaps this log is useful?
https://buildkite.com/julialang/fourierflows-dot-jl/builds/213#e0fcfca5-415c-48c3-8b0b-56aad944ec65/252-450

I can try to make a MWE!

**Comment by navidcy** [comment]
Note that the buildkite failures above with 3.4.2 and 3.5.0 were from some trivial `show()` method that needed updating. But the failure with 3.7.0 relates to `mul!` with CuArrays and fftplans....

**Review by liasiegelman — APPROVED** [review]

**Comment by navidcy** [comment]
@maleadt, I tested it using CUDA#master [@ 430787](https://github.com/JuliaGPU/CUDA.jl/commit/430787db772f83eaeac226b591b9ded9f979f652) and seems to work fine! So if you tag 3.7.1 I'll add a compat entry

```Julia
CUDA = "^1, ^2.4.2, 3.0.0-3.6.4, ^3.7.1"
```
which should do the job. ;)

**Comment by maleadt** [comment]
https://github.com/JuliaRegistries/General/pull/53274

**Pull request merged**
