### PR TITLE
Fix bug in on_grid() utility function

### LINKED ISSUE #256: Bug in on_grid
For 2D or 3D grids the `on_grid()` function does not work on GPU.

```
julia> grid = TwoDGrid(GPU(), 10, 2π);

julia> FourierFlows.on_grid(f, grid)
ERROR: scalar getindex is disallowed
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] assertscalar(::String) at /g/data/v45/nc3020/.julia/packages/GPUArrays/WV76E/src/host/indexing.jl:41
 [3] getindex at /g/data/v45/nc3020/.julia/packages/GPUArrays/WV76E/src/host/indexing.jl:96 [inlined]
 [4] getindex at /g/data/v45/nc3020/.julia/packages/GPUArrays/WV76E/src/host/indexing.jl:117 [inlined]
 [5] _broadcast_getindex at ./broadcast.jl:614 [inlined]
 [6] _getindex at ./broadcast.jl:644 [inlined]
 [7] _broadcast_getindex at ./broadcast.jl:620 [inlined]
 [8] getindex at ./broadcast.jl:575 [inlined]
 [9] copy at ./broadcast.jl:876 [inlined]
 [10] materialize(::Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2},Nothing,typeof(f),Tuple{CuArray{Float64,2},CuArray{Float64,2}}}) at ./broadcast.jl:837
 [11] on_grid(::Function, ::TwoDGrid{Float64,CuArray{Float64,2},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},CUDA.CUFFT.cCuFFTPlan{Complex{Float64},-1,false,2},CUDA.CUFFT.rCuFFTPlan{Float64,-1,false,2}}) at /g/data/v45/nc3020/.julia/packages/FourierFlows/rKnSO/src/utils.jl:255
 [12] top-level scope at REPL[62]:1
```

### PR DESCRIPTION
**Pull request by navidcy**
`CUDA.@allowscalar` is not just for tests.

Closes #256

### CODE REVIEW

**Comment by glwagner** [comment]
Should we call these kinds of issues "limitations" rather than "bugs"? I think "bug" implies incorrect behavior.

**Comment by navidcy** [comment]
The code was breaking though. It wasn’t that the functionality was missing. :)

**Comment by glwagner** [comment]
I'm just advocating for defining a "bug" as something that produces wrong results like `2 + 2 = 5`, but we can take a broader view of "bugs" if you prefer.

**Comment by navidcy** [comment]
OK I see your point.

**Pull request merged**
