### PR TITLE
Fix TracerAdvDiff module

### PR DESCRIPTION
**Pull request by navidcy**
This PR fixes the `TracerAdvDiff` module. In particular:

- fixes some bugs in the `traceradvdiff.jl`
- adds tests for `TracerAdvDiff`
- adds a simple example that simulates advection diffusion equation for a time-independent cellular flow

### CODE REVIEW

**Comment by glwagner** [comment]
I think this a good idea. I think my original reasoning was that the algorithm to compute the "conservation form" is slightly faster. But if it is it must only be by some extremely small amount. I can make this change.

**Comment by navidcy** [comment]
Good. Don’t forget to change the docs then before merging. Or let me know and I can do it.

**Comment by navidcy** [comment]
How about a `cu_cellular.jl` example in `examples/cudaexamples`?

**Comment by navidcy** [comment]
@glwagner 
This part of the `Problem()` function is problematic:
https://github.com/FourierFlows/FourierFlows.jl/blob/7ed886f1ef72626357bbab68bdb18611dbd6d6cc/src/physics/traceradvdiff.jl#L27-L35

Consider this minimal example:
```julia
julia> function mytest(testvar)
       if testvar
         u(x, y) = 0.0
       else
         u(x, y, t) = 1.0
       end
       println(methods(u))
       end
mytest (generic function with 1 method)

julia> mytest(true)
# 2 methods for generic function "(::u)":
(::#u#1)(x, y) in Main at REPL[10]:3
(::#u#1)(x, y, t) in Main at REPL[10]:5

julia> mytest(false)
ERROR: UndefVarError: u not defined
Stacktrace:
 [1] mytest(::Bool) at ./REPL[10]:7
```

When `true` both `u(x, y)` **and** `u(x, y, t)` are created; when false none of them....
We are doing something wrong here.

**Comment by navidcy** [comment]
This works though:
```julia
julia> function mytest(testvar)
       usteady(x, y) = 0.0;
       utime(x, y, t) = 0.1;
       if testvar
         u = usteady
       else
         u = utime
       end
       println(methods(u))
       end
mytest (generic function with 1 method)

julia> mytest(true)
# 1 method for generic function "(::usteady)":
(::#usteady#1)(x, y) in Main at REPL[36]:2

julia> mytest(false)
# 1 method for generic function "(::utime)":
(::#utime#2)(x, y, t) in Main at REPL[36]:3
```

I'm modifying `Problem()` function to address this...

**Comment by navidcy** [comment]
@glwagner: Because of the large uncertainty with the Cuda functionality (we don't really test that part of the code yet) I'm very tempted to move *all* Cuda stuff in a different branch, merge this PR, and then work on the Cuda stuff separately and submit a new PR for those. What do you think?

**Comment by navidcy** [comment]
All CUDA implementation for `TracerAdvDiff` module moved in branch `AddCudaFunctionalityTracerAdvDiff`  (https://github.com/FourierFlows/FourierFlows.jl/tree/AddCudaFunctionalityTracerAdvDiff)

@glwagner: if you don't have anything else to add, I'll merge the PR

**Comment by navidcy** [comment]
The issue raised in the comments before is know and discussed here: https://github.com/JuliaLang/julia/issues/15602.

**Pull request merged**
